Backup/Dbz.HomeworkHub.Frontend/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dbz.HomeworkHub.Frontend.Controllers
{
    /// <summary>
    /// Controller für die Verwaltung der Administration
    /// </summary>
    public class AdminController : BaseController
    {
        /// <summary>
        /// Standardmethode für Startseite der Administration
        /// </summary>
        /// <returns>Startansicht der Administration</returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

Backup/Dbz.HomeworkHub.Frontend/Controllers/HomeworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dbz.HomeworkHub.Frontend.Controllers
{
    /// <summary>
    /// Kontroller für die Verwaltung von Hausaufgaben
    /// </summary>
    public class HomeworkController : BaseController
    {
        /// <summary>
        /// Liefert die Übersicht aller offenen Hausaufgaben
        /// </summary>
        /// <returns>Ansicht aller offenen Hausaufgaben</returns>
        public ActionResult Open()
        {
            return View();
        }

        /// <summary>
        /// Liefert die Übersicht aller Hausaufgaben im System
        /// </summary>
        /// <returns>Ansicht aller Hausaufgaben</returns>
        public ActionResult All()
        {
            return View();
        }

    }
}

Backup/Dbz.HomeworkHub.Frontend/Views/Shared/ViewLoginControl.cshtml
@{
    using (var form = Html.BeginForm("Login", "Account", FormMethod.Post, new { @class = "form-inline", role = "form" }))
    {
    <div class="form-group">
        <label class="sr-only" for="password">E-Mailaddresse</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Hier anmelden (E-Mail)...">
    </div>
    <div class="form-group">
        <label class="sr-only" for="username">Passwort</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Passwort...">
    </div>
    <button id="smallLoginFormSignIn" type="submit" class="btn btn-success">Sign in</button>
    }
}

Backup/Dbz.HomeworkHub.Frontend/Views/Shared/ViewLoginLargeControl.cshtml
<div class="largeLoginForm">
    <h3>Hier anmelden</h3>
    <p>
        Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you.    
    </p>
    @{
        using (var form = Html.BeginForm("Login", "Account", FormMethod.Post, new { @class = "form-inline", role = "form" }))
        {
            <br />
            <div>
                <label for="loginEMail">E-Mailaddresse</label>
                <input type="text" class="form-control" id="loginEMail" name="username" placeholder="E-Mail ... ">
            </div>
            <br />
            <div>
                <label for="loginPassword">Passwort</label>
                <input type="password" class="form-control" id="loginPassword" name="password" placeholder="Passwort... ">
            </div>
            <br />
            <button id="loginFormLoginButton" class="btn btn-success" type="submit">Anmelden</button>
            <button id="loginFormRegisterNowButton" data-toggle="modal" href="#registerUserDialog" class="btn btn-primary">Jetzt Registrieren!</button>  
        }
    }
</div>


<div class="modal fade" id="registerUserDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Neuer Zugang registrieren</h4>
            </div>
            <div class="modal-body">
                <div id="registerErrors" class="alert alert-danger" style="display: none;">
                    <ul data-bind="foreach: NewAccountModel.Errors.Items">
                        <li data-bind="text: $data"></li>
                    </ul>
                </div>
                <p>
                    Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. 
                </p>
                <form role="form" class="form-horizontal">
                    <div class="form-group">
                        <label for="registerUserDialogVorname" class="col-sm-4 control-label">Vorname</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="registerUserDialogVorname" data-bind="value: NewAccountModel.Vorname">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="registerUserDialogNachname" class="col-sm-4 control-label">Nachname</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="registerUserDialogNachname" data-bind="value: NewAccountModel.Nachname">
                        </div>
                    </div>
                    <br />
                    <br />
                    <div class="form-group">
                        <label for="registerUserDialogEMail" class="col-sm-4 control-label">E-Mail</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="registerUserDialogEMail" data-bind="value: NewAccountModel.EMail">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="registerUserDialogEMailWH" class="col-sm-4 control-label">E-Mail widerholen</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="registerUserDialogEMailWH" data-bind="value: NewAccountModel.EMailWh">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="registerUserDialogPasswort" class="col-sm-4 control-label">Passwort</label>
                        <div class="col-sm-6">
                            <input type="password" class="form-control" id="registerUserDialogPasswort" data-bind="value: NewAccountModel.Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="registerUserDialogPasswortWH" class="col-sm-4 control-label">Passwort widerholen</label>
                        <div class="col-sm-6">
                            <input type="password" class="form-control" id="registerUserDialogPasswortWH" data-bind="value: NewAccountModel.PasswordWH">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="registerUserDialogPasswortWH" class="col-sm-4 control-label"></label>
                        <div class="col-sm-8">
                            <input id="registerUserDialogCheckbox" type="checkbox" />
                            Ich akzeptiere die Nutzungsbedinungen
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="registerFormNewAccountCancelButton" type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                <button id="registerFormNewAccountButton" type="button" class="btn btn-primary">Registrieren</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">


    $(document).ready(function () {

        $("#registerFormNewAccountButton").click(function () {
            registerNewAccount();
        });

    });

    function registerNewAccount() {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Register", "Account")',
            data: model.NewAccountModel.JsonObj(),
            dataType: 'json',
            success: function (data) {

                model.NewAccountModel.Merge(data);

                if (model.NewAccountModel.Errors.HasErrors() == false) {
                    model.NewAccountModel.Clear();
                    $('#registerUserDialog').modal('hide');
                       
                    bootbox.dialog({
                        message: "Ihr Zugang zu unserem Portal wurde erstellt. Sie können sich nun über die Anmeldefunktion auf der Startseite einloggen.",
                        title: "Zugang erfolgreich erstellt",
                        buttons: {
                            main: {
                                label: "Ok",
                                className: "btn-default",
                                callback: function () {
                                }
                            }
                        }
                    });

                }
                else {
                    $("#registerErrors").fadeIn();
                }
            }
        });
    }

</script>

Backup/Dbz.HomeworkHub.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Homework</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")" rel="stylesheet">
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootbox.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/knockout.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/viewmodels.js")" type="text/javascript" ></script>
</head>
<body>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")" >Homework Hub</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li></li>
                    <li>@Html.ActionLink("Offene Hausaufgaben", "Open", "Homework")</li>
                    <li>@Html.ActionLink("Alle Hausaufgaben", "All", "Homework")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @{ 
                        if (ViewBag.CurrentUser == null)
                        {
                            <li style="padding-top: 8px;">
                            @Html.Partial("ViewLoginControl")
                            </li>
                        } else {
                            Dbz.HomeworkHub.Frontend.Models.CurrentUserModel cum = ViewBag.CurrentUser as Dbz.HomeworkHub.Frontend.Models.CurrentUserModel;
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">@String.Format("{0}, {1}", cum.Nachname, cum.Vorname)<b class="caret"></b></a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Meine Hausaufgabe</a></li>
                                <li><a href="#">Von mir erstelle Lösungen</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Mein Zugang</a></li>
                                <li>
                                    @Html.ActionLink("Administration", "Index", "Admin")
                                </li>
                                <li class="divider"></li>
                                <li>
                                    @Html.ActionLink("Abmelden", "Logout", "Account")
                                </li>
                              </ul>
                            </li>
                        }
                    }
                </ul>



            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
    <div class="page">
        <div class="innerPage">
            <div class="innerPage2">
                <div class="headerArea">
                </div>
                <div class="smallDevider"></div>
                <div id="main">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <div id="footer">
        Copyright (c) 2013 by Division By Zero. Alle Rechte vorbehalten!
    </div>
</body>


<script type="text/javascript">

    $(document).ready(function () {
        // DataBinding durchführen
        ko.applyBindings(model);
    });

</script>

</html>